### ISSUE TITLE
Wishlist detail page does not show the product that are added to wishlist

### ISSUE THREAD

**Issue by aniruddhasm** [dlerm/shopify-wishlist#1]
Hello,
I am trying to implement this project in my shopify store. I have followed all steps mentioned in readme.md
The `is_active` class is geeting added when I click on the wishlist button. But when I check on detail page. It display no products added.

Please help I am stuck

**Comment by dlerm** [comment]
In the Wishlist.js file, find this function:
```
var loadWishlist = function () {
    if (window.location.href.indexOf('pages/wishlist')) {
      displayOnlyWishlistItems();
      $('.wishlist-loader').fadeOut(2000, function () {
        $('.wishlist-grid').addClass('is_visible');
        $('.wishlist-hero').addClass('is_visible');
        if (numProductTiles == 0) {
          $('.wishlist-grid--empty-list').addClass('is_visible');
        } else {
          $('.wishlist-grid--empty-list').hide();
        }
      });
    }
  };
```
And change the line:
` if (window.location.href.indexOf('pages/wishlist')) { `
to:
` if (window.location.href.indexOf('pages/wishlist') > -1) { `
Also, make sure your wishlist page has a page handle of 'wishlist'.

You can also check whether items are being added to the localStorage by entering this in the browser console:
```
var wishlist = localStorage.getItem('user_wishlist') || [];
console.log(JSON.stringify(wishlist));
```

Let me know if that helps.

**Comment by aniruddhasm** [comment]
Thanks for reply.
I've tested the code and yes the items are getting added to localStorage. But they are not displaying on detail page.

I am still facing the same issue.

**product.tile.liquid**
```
<div class="product-tile-container wishlist-tile-container" data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">
  <div class="product-tile wishlist-tile">
    <div class="product-tile--tile-media">
      <a class="tile-media--media-link" href="{{ product.url }}">
        <div class="media-link--image">
          <img class="image--main" src="{{ product.featured_image | product_img_url: 'grande' }}" alt="{{ product.title }}">
        </div>
      </a>
    </div>
    <div class="product-tile--tile-content flex">
      <div class="tile-content--text">
        <p class="text--title black">{{ product.title }}</p>
        {% if product.compare_at_price > product.price %}
          <p class="text--price">
            <span class="price--compare strike-through">{{ product.compare_at_price | money }}</span> <span class="price--sale">{{ product.price | money }}</span>
          </p>
        {% else %}  
          <p class="text--price">{{ product.price | money }}</p>
        {% endif %}
      </div>
      <div class="product-tile--tile-actions flex">
        {% include 'wishlist-button'%}
        <a class="action--quick-cart tile-actions--btn flex cart-btn" href="/cart/add?id={{ product.selected_or_first_available_variant.id }}&quantity=1">Add To Cart</a>
      </div>
    </div>
  </div>  
</div>
```

Above code is from product.tile.liquid. When I remove the second div from top with class 
**product-tile wishlist-tile** I am able to all products of my store instead of products added to the wishlist.

Please let me know if I'm missing something to do.
Please help.

**Comment by dlerm** [comment]
So the way that this wishlist page works is:
1) All products from the store are initially loaded but hidden with css
2) The **Wishlist.js** function **displayOnlyWishlistItems** will then check for the data-product-handle attribute on each product tile

- If the product handle matches one found in the wishlist localStorage array, that product title will become visible
- If the product handle is not found in the localStorage array, that product tile is removed from the DOM

Are the data-product-handle attributes being populated correctly?

`<div class="product-tile-container wishlist-tile-container" data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">`

Also make sure that the function  **loadWishlist** is firing this code:
` $('.wishlist-grid').addClass('is_visible');`
Which make the tiles visible

**Comment by aniruddhasm** [comment]
Thanks for reply,
Every thing you said is working fine.

The below structure is created as empty on my wishlist detail page.
```
<div data-product-handle="mrf-genius-kohli-limited-edition-players-grade-batting-gloves" data-product-id="8286436102" class="product-tile-container wishlist-tile-container">    
</div>

```
This is the same handle of my product on product listing page.
Thanks

**Comment by tefugen** [comment]
I have problem in this wishlist normally wishlist is added but in this all products go the wishlist page automatically i need when the user select the product means that is added to wishlist i need that please help me to how find the solution

my store name : https://biplecomtesting.myshopify.com

login 
username : Demo321@gmail.com
password:demodemo

kindly check please update ASAP

**Comment by tefugen** [comment]
page.wish-list.liquid
<div class="full-width-container wishlist-container">
  
  <div class="wishlist-hero">
    <h1 class="wishlist-hero--title">{{ page.title }}</h1>
  </div>
  
  <div class="wishlist-grid flex">
   
    {% for product in collections.all.products %}

			
<div class="product-tile-container wishlist-tile-container" data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">
  <div class="product-tile wishlist-tile">
    <div class="product-tile--tile-media">
      <a class="tile-media--media-link" href="{{ product.url }}">
        <div class="media-link--image">
          <img class="image--main" src="{{ product.featured_image | product_img_url: 'grande' }}" alt="{{ product.title }}">
        </div>
      </a>
    </div>
    <div class="product-tile--tile-content flex">
      <div class="tile-content--text">
        <p class="text--title black">{{ product.title }}</p>
        {% if product.compare_at_price > product.price %}
          <p class="text--price">
            <span class="price--compare strike-through">{{ product.compare_at_price | money }}</span> <span class="price--sale">{{ product.price | money }}</span>
          </p>
        {% else %}  
          <p class="text--price">{{ product.price | money }}</p>
        {% endif %}
      </div>
      <div class="product-tile--tile-actions flex">
          <a class="action--quick-cart tile-actions--btn flex cart-btn" href="/cart/add?id={{ product.selected_or_first_available_variant.id }}&quantity=1">Add To Cart</a>
      </div>
    </div>
  </div>  
</div>
 
 		{% endfor %}
 	
  
    <div class="wishlist-grid--empty-list flex">
      <div class="empty-list--info">
          <a class="btn empty-list--btn" href="/collections/all">Start Shopping</a>
      </div>
    </div>
  </div>
  
  
Wishlist.js.liquid
;(function (Wishlist, $) {

  var $wishlistButton = $('.wishlist-btn');
  var $wishlistTile = $('.wishlist-tile');
  var numProductTiles = $wishlistTile.length;
  var wishlist = localStorage.getItem('user_wishlist') || [];
  if (wishlist.length > 0) {
    wishlist = JSON.parse(localStorage.getItem('user_wishlist'));
  }

  /*
   * Update button to show current state (gold for active)
   */   
  var animateWishlist = function (self) {
    $(self).toggleClass('is-active');
  };

  /*
   * Add/Remove selected item to the user's wishlist array in localStorage
   * Wishlist button class 'is-active' determines whether or not to add or remove
   * If 'is-active', remove the item, otherwise add it
   */   
  var updateWishlist = function (self) {
    var productHandle = $(self).attr('data-product-handle');
    var isRemove = $(self).hasClass('is-active');
    /* Remove */
    if (isRemove) {
      var removeIndex = wishlist.indexOf(productHandle);
      wishlist.splice(removeIndex, 1);
      localStorage.setItem('user_wishlist', JSON.stringify(wishlist));
    }
    /* Add */ 
    else {
      wishlist.push(productHandle);
      localStorage.setItem('user_wishlist', JSON.stringify(wishlist));
    }
    console.log(JSON.stringify(wishlist));
  };

  /*
   * Loop through wishlist buttons and activate any items that are already in user's wishlist
   * Activate by adding class 'is-active'
   * Run on initialization
   */   
  var activateItemsInWishlist = function () {
    $wishlistButton.each(function () {
      var productHandle = $(this).attr('data-product-handle');
      if (wishlist.indexOf(productHandle) > -1) {
        $(this).addClass('is-active');
      }
    });
  };

  /*
   * Loop through product titles and remove any that aren't a part of the wishlist
   * Decrement numProductTiles on removal
   */   
  var displayOnlyWishlistItems = function () {
    $wishlistTile.each(function () {
      var productHandle = $(this).attr('data-product-handle');
      if (wishlist.indexOf(productHandle) === -1) {
        $(this).remove();
        numProductTiles--;
      }
    });
  };

  /*
   * Check if on the wishlist page and hide any items that aren't a part of the wishlist
   * If no wishlist items exist, show the empty wishlist notice
   */   
  var loadWishlist = function () {
    if (window.location.href.indexOf('pages/wishlist') > -1) {
      displayOnlyWishlistItems();
      $('.wishlist-loader').fadeOut(2000, function () {
        $('.wishlist-grid').addClass('is_visible');
        $('.wishlist-hero').addClass('is_visible');
        if (numProductTiles == 0) {
          $('.wishlist-grid--empty-list').addClass('is_visible');
        } else {
          $('.wishlist-grid--empty-list').hide();
        }
      });
    }
  };

  var bindUIActions = function () {
    $wishlistButton.click(function (e) {
      e.preventDefault();
      updateWishlist(this);
      animateWishlist(this);
    });
  };

  Wishlist.init = function () {
    bindUIActions();
    activateItemsInWishlist();
    loadWishlist();
  };

}(window.Wishlist = window.Wishlist || {}, jQuery, undefined));

**Comment by dlerm** [comment]
@aniruddhasm So the issue is that product tiles that display have no inner content?

**Comment by aniruddhasm** [comment]
Thanks for reply.

I've now resolved the issue by making small changes in the product-tile.liquid file. Please find the explanation below.

~~~
var $wishlistTile = $('.wishlist-tile');
var displayOnlyWishlistItems = function () {
    $wishlistTile.each(function () {
      var productHandle = $(this).attr('data-product-handle');
      if (wishlist.indexOf(productHandle) === -1) {
        $(this).remove();
        numProductTiles--;
      }
    });
  };
~~~

This was your old structure
~~~
<div class="product-tile-container wishlist-tile-container" data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">
  <div class="product-tile wishlist-tile">
~~~

There is no attribute **data-product-handle** added to **product-tile wishlist-tile** class.
So I removed the  **data-product-handle="{{ product.handle }}"** from **product-tile-container** and added to **product-tile**

This is how my new structure looks
~~~
<div class="product-tile-container wishlist-tile-container">
  <div class="product-tile wishlist-tile"  data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">
~~~

**Comment by dlerm** [comment]
@aniruddhasm Excellent! Glad to hear its working for you now. Feel free to ask more questions if you come across any other issues.

**Comment by dlerm** [comment]
@tefugen Could you give me some more details on the issues. Please also update your code with the updated repo code.

**Comment by tefugen** [comment]
**Wishlist.js**

;(function (Wishlist, $) {

  var $wishlistButton = $('.wishlist-btn');
 var $wishlistTile = $('.wishlist-tile-container');
  var numProductTiles = $wishlistTile.length;
  var wishlist = localStorage.getItem('user_wishlist') || [];
  if (wishlist.length > 0) {
    wishlist = JSON.parse(localStorage.getItem('user_wishlist'));
  }

  /*
   * Update button to show current state (gold for active)
   */   
  var animateWishlist = function (self) {
    $(self).toggleClass('is-active');
  };

  /*
   * Add/Remove selected item to the user's wishlist array in localStorage
   * Wishlist button class 'is-active' determines whether or not to add or remove
   * If 'is-active', remove the item, otherwise add it
   */   
  var updateWishlist = function (self) {
    var productHandle = $(self).attr('data-product-handle');
    var isRemove = $(self).hasClass('is-active');
    /* Remove */
    if (isRemove) {
      var removeIndex = wishlist.indexOf(productHandle);
      wishlist.splice(removeIndex, 1);
      localStorage.setItem('user_wishlist', JSON.stringify(wishlist));
    }
    /* Add */ 
    else {
      wishlist.push(productHandle);
      localStorage.setItem('user_wishlist', JSON.stringify(wishlist));
    }
    console.log(JSON.stringify(wishlist));
  };

  /*
   * Loop through wishlist buttons and activate any items that are already in user's wishlist
   * Activate by adding class 'is-active'
   * Run on initialization
   */   
  var activateItemsInWishlist = function () {
    $wishlistButton.each(function () {
      var productHandle = $(this).attr('data-product-handle');
      if (wishlist.indexOf(productHandle) > -1) {
        $(this).addClass('is-active');
      }
    });
  };

  /*
   * Loop through product titles and remove any that aren't a part of the wishlist
   * Decrement numProductTiles on removal
   */   
  var displayOnlyWishlistItems = function () {
    $wishlistTile.each(function () {
      var productHandle = $(this).attr('data-product-handle');
      if (wishlist.indexOf(productHandle) === -1) {
        $(this).remove();
        numProductTiles--;
      }
    });
  };

  /*
   * Check if on the wishlist page and hide any items that aren't a part of the wishlist
   * If no wishlist items exist, show the empty wishlist notice
   */   
  var loadWishlist = function () {
    if (window.location.href.indexOf('pages/wishlist') > -1) {
      displayOnlyWishlistItems();
      $('.wishlist-loader').fadeOut(2000, function () {
        $('.wishlist-grid').addClass('is_visible');
        $('.wishlist-hero').addClass('is_visible');
        if (numProductTiles == 0) {
          $('.wishlist-grid--empty-list').addClass('is_visible');
        } else {
          $('.wishlist-grid--empty-list').hide();
        }
      });
    }
  };

  var bindUIActions = function () {
    $wishlistButton.click(function (e) {
      e.preventDefault();
      updateWishlist(this);
      animateWishlist(this);
    });
  };

  Wishlist.init = function () {
    bindUIActions();
    activateItemsInWishlist();
    loadWishlist();
  };

}(window.Wishlist = window.Wishlist || {}, jQuery, undefined));

**page.wishlist.liquid**

<div class="full-width-container wishlist-container">
  
  <div class="wishlist-hero">
    <h1 class="wishlist-hero--title">{{ page.title }}</h1>
  </div>
  
  <div class="wishlist-grid flex">
    {% for product in collections.all.products %}
      {% include 'product-tile' %}
    {% endfor %}
    <div class="wishlist-grid--empty-list flex">
      <div class="empty-list--info">
        <h6 class="empty-list--text black">Looks like you haven't started a wishlist yet...</h6>
        <a class="btn empty-list--btn" href="/collections/all">Start Shopping</a>
      </div>
    </div>
  </div>
  
  <div class="wishlist-loader">
    <img class="wishlist-loader--image" src="{{ 'icn-wishlist.svg' | asset_url }}" alt="Wishlist loading">
    <p class="wishlist-loader--text">Loading your customized wishlist...</p>
  </div>
</div>

**product-tile.liquid**
<div class="product-tile-container wishlist-tile-container" data-product-id="{{ product.id }}" data-product-handle="{{ product.handle }}">
  <div class="product-tile wishlist-tile">
    <div class="product-tile--tile-media">
      <a class="tile-media--media-link" href="{{ product.url }}">
        <div class="media-link--image">
          <img class="image--main" src="{{ product.featured_image | product_img_url: 'grande' }}" alt="{{ product.title }}">
        </div>
      </a>
    </div>
    <div class="product-tile--tile-content flex">
      <div class="tile-content--text">
        <p class="text--title black">{{ product.title }}</p>
        {% if product.compare_at_price > product.price %}
          <p class="text--price">
            <span class="price--compare strike-through">{{ product.compare_at_price | money }}</span> <span class="price--sale">{{ product.price | money }}</span>
          </p>
        {% else %}  
          <p class="text--price">{{ product.price | money }}</p>
        {% endif %}
      </div>
      <div class="product-tile--tile-actions flex">
          <a class="action--quick-cart tile-actions--btn flex cart-btn" href="/cart/add?id={{ product.selected_or_first_available_variant.id }}&quantity=1">Add To Cart</a>
      </div>
    </div>
  </div>  
</div>

**wishlist-btn.liquid**
<a class="wishlist-btn" href="#" data-product-handle="{{ product.handle }}">
<a class="action--quick-cart tile-actions--btn flex cart-btn " href="/pages/wishlist?id={{ product.selected_or_first_available_variant.id }}&quantity=1">Add To Wishlist</a>
</a>

**Comment by tefugen** [comment]
Please anyone help for my wishlist problem above code is my wishlist i am used.

**Comment by dlerm** [comment]
@tefugen If you post code please use the "Insert Code" button so that it remains formatted and readable. 

Also, have you clicked the add to wishlist button? That will populate the wishlist localStorage array, which will then be used to populate the wishlist page.

**Comment by anilviradiya** [comment]
If 200+ Plus product that time wishlist is not working because of when page load that time only loads 20 products.
If users added 199 number product to wishlist then the wishlist show empty.
anyone has a solution for this.
Thanks
