### ISSUE TITLE
[Warehouse Theme] - Product not displayed on Wishlist page

### ISSUE THREAD

**Issue by Dovriik** [dlerm/shopify-wishlist#38]
Hi dlerm!
I follow your instructions and manage to have the console run correctly but the Wishlist page doesn't render the item, just an empty box (two of them in the picture below, as you can see).

![Empty Wishlist Page](https://user-images.githubusercontent.com/115712990/195599600-05eef788-a542-4201-8980-8fe6381cc67d.png)

Here is the code for the product-card-template.liquid:
`{% comment %}
  Shopify Wishlist
  Usage:
    - Replace the snippet name ('product-card') with your existing product card snippet
    - Pass the product object as a snippet variable named 'product'
{% endcomment %}
{%- render 'product-info', product: product -%}

{% schema %}
  {
    "templates": ["product"]
  }
{% endschema %}`

Here is the link to the code for the product-info.liquid (since it's long, I will use Pastebin). I paste your line of code to render the wishlist button on line 22:
https://pastebin.com/F9s1p6q7

Here is the image of the heart icon, but it's statis, there is no change whether I click on it or not:

![image](https://user-images.githubusercontent.com/115712990/195775599-7d2649b8-a6e7-4c35-a4d5-f8e48002eaf6.png)

Also, in your Wishlist.js, I need to modified it a bit (row 6, I have changed in the selectors list the productCard: '.product-card' to productCard:'.card'). Since if I don't made this modification, this will happen in the browser console:
![image](https://user-images.githubusercontent.com/115712990/195608748-67a73d4c-5d12-4c1a-b276-4f877ca217f2.png)

Maybe because I use the wrong product snippet file to begin with? I don't really know since I have no coding background.
Also, my apologies if my issues post is a mess, this is the first time I use Github.

Thank you very much for your help and support!

**Comment by dlerm** [comment]
@Dovriik Looking at you pastebin file, it seems that product card snippet you are referencing  ("product-info") is actually meant for your product template instead of for collections (product listings). It has many references to `section` variables that would not exist in the context of the `product.card.json` template and `product-card-template` section defined in the wishlist project code.

The product card you are looking for (based on Warehouse theme) will have the class "product-item" on it. Unfortunately I'm not sure what the file name is as I don't have access to the warehouse theme code, just the [demo store pages](https://themes.shopify.com/themes/warehouse/styles/metal/preview?surface_detail=large-inventory&surface_inter_position=1&surface_intra_position=9&surface_type=collection).
